version: 2.1

orbs:
    node: circleci/node@5.0.2
    heroku: circleci/heroku@0.0.10

jobs:
    build_and_jest:
        docker:
            - image: cimg/node:16.15.0
        environment:
            - NODE_ENV: development
        steps:
            - checkout
            - restore_cache: #cache dependencies to skip reinstall
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Run test (Jest)
                  command: npm run test
            - persist_to_workspace:
                  root: .
                  paths:
                      - .nyc_output/*
            - run: ls ./.nyc_output
    create_report:
        docker:
            - image: cimg/node:16.15.0
        environment:
            - NODE_ENV: development
        steps:
            - checkout
            - attach_workspace:
                  at: ./
            - restore_cache: #cache dependencies to skip reinstall
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Create coverage report
                  command: npm run create-report
            - store_artifacts:
                  path: /coverage
            - run: ls ./.nyc_output
    e2e:
        docker:
            - image: mcr.microsoft.com/playwright:v1.22.0-focal
        environment:
            NODE_ENV: development # Needed if playwright is in `devDependencies`
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: Run server in background
                  command: npm run dev
                  background: true
            - run: sleep 10
            - run:
                  name: Run test (Playwright)
                  command: npm run test-e2e
            - persist_to_workspace:
                  root: .
                  paths:
                      - .nyc_output/*
            - run: ls ./.nyc_output
            - store_artifacts:
                  path: /tmp/.nyc_output

workflows:
    build_test_deploy:
        jobs:
            - build_and_jest
            - e2e:
                  requires:
                      - build_and_jest
            - create_report:
                  requires:
                      - e2e
            - heroku/deploy-via-git:
                  requires:
                      - create_report
                  filters:
                      branches:
                          only: main
