version: 2.1
orbs:
    node: circleci/node@5.0.2
    heroku: circleci/heroku@0.0.10

jobs:
    build:
        docker:
            - image: circleci/node:16.15.0
        steps:
            - checkout
            - restore_cache: #cache dependencies to skip reinstall
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Run test
                  command: npm run test
workflows:
    heroku_deploy:
        jobs:
            - build
            - heroku/deploy-via-git:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
