version: 2.1

orbs:
    node: circleci/node@5.0.2
    heroku: circleci/heroku@0.0.10

jobs:
    build_and_test:
        docker:
            - image: cimg/node:16.15.0
        environment:
            - NODE_ENV: development
        steps:
            - checkout
            - restore_cache: #cache dependencies to skip reinstall
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Run server in background
                  command: npm run dev
                  background: true
            - run:
                  name: Run test (Jest)
                  command: npm run test
            - run:
                  name: Run test (Playwright)
                  command: npm run test-e2e
            - run:
                  name: Create coverage report
                  command: npm run create-report
            - store_artifacts:
                  path: /coverage

workflows:
    build_test_deploy:
        jobs:
            - build_and_test
            - heroku/deploy-via-git:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
